"""Initial migration

Revision ID: 0e3da540513a
Revises: 
Create Date: 2025-03-16 14:53:00.489253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3da540513a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deteccion_paquetes',
    sa.Column('ID_Deteccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Distancia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Estado', sa.Enum('Detectado', 'No detectado'), nullable=False),
    sa.Column('Fecha_Hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID_Deteccion')
    )
    op.create_table('productos',
    sa.Column('ID_Producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Stock', sa.Integer(), nullable=False),
    sa.Column('Fecha_Registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID_Producto')
    )
    op.create_table('usuarios',
    sa.Column('ID_Usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Apellido', sa.String(length=100), nullable=False),
    sa.Column('Correo', sa.String(length=100), nullable=False),
    sa.Column('Telefono', sa.String(length=15), nullable=True),
    sa.Column('Direccion', sa.String(length=255), nullable=True),
    sa.Column('Contraseña', sa.String(length=255), nullable=False),
    sa.Column('Rol', sa.Enum('Cliente', 'Empleado', 'Administrador'), nullable=False),
    sa.Column('Fecha_Registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID_Usuario'),
    sa.UniqueConstraint('Correo')
    )
    op.create_table('clasificacion_paquetes',
    sa.Column('ID_Clasificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Producto', sa.Integer(), nullable=False),
    sa.Column('Etiqueta_Color', sa.Enum('Rojo', 'Verde'), nullable=False),
    sa.Column('Accion', sa.Enum('Izquierda', 'Derecha'), nullable=False),
    sa.Column('Fecha_Hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Producto'], ['productos.ID_Producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_Clasificacion')
    )
    op.create_table('datos_remotos',
    sa.Column('ID_Dato', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Deteccion', sa.Integer(), nullable=True),
    sa.Column('ID_Clasificacion', sa.Integer(), nullable=True),
    sa.Column('Estado_Conexion', sa.Enum('Exitoso', 'Fallido'), nullable=True),
    sa.Column('Fecha_Hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Clasificacion'], ['clasificacion_paquetes.ID_Clasificacion'], ),
    sa.ForeignKeyConstraint(['ID_Deteccion'], ['deteccion_paquetes.ID_Deteccion'], ),
    sa.PrimaryKeyConstraint('ID_Dato')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datos_remotos')
    op.drop_table('clasificacion_paquetes')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('deteccion_paquetes')
    # ### end Alembic commands ###
